"""Add address_id to tickets table

Revision ID: 644d586ea8dd
Revises: f3effdbfc865
Create Date: 2025-10-29 01:44:35.307688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644d586ea8dd'
down_revision: Union[str, Sequence[str], None] = 'f3effdbfc865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tickets', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'address', ['address_id'], ['address_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'address_id')
    # ### end Alembic commands ###
