"""Add address table cleanly

Revision ID: f3effdbfc865
Revises: 
Create Date: 2025-10-28 12:38:28.309040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3effdbfc865'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_issue_categories_category_id'), 'issue_categories', ['category_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('customer', 'engineer', 'admin', 'manager', 'agent'),
               type_=sa.Enum('customer', 'agent', 'engineer', 'manager', 'admin', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('customer', 'agent', 'engineer', 'manager', 'admin', name='userrole'),
               type_=mysql.ENUM('customer', 'engineer', 'admin', 'manager', 'agent'),
               nullable=True)
    op.drop_index(op.f('ix_issue_categories_category_id'), table_name='issue_categories')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
